"""The headline figures in CLAUDE.md must appear in the report that produced them.

CLAUDE.md is the source of truth for how this lab is operated, and it is written
by hand. The reports under `data/outputs/` are regenerated by scripts. Nothing
compared the two, and on 2026-09-02 and 2026-09-03 that cost four separate
retractions of numbers this file was still quoting:

* `tackles_assists` was described as replicating at +12.4%/+11.2%/+12.6% and
  being "structurally unmeasurable". The reports had said −1.0% over 2,758
  held-out bets since its summation bug was fixed.
* The forecast-skill table read 74,345 bets and Brier 0.26057/0.22703. The
  report read 78,253 and 0.26106/0.22782 — the settlement-join fix had changed
  the bet population and every count with it.
* The null baseline was quoted at −9.47% in two places against a report saying
  −9.29% on the same 366,725 bets.
* Two figures in the over-shading paragraph appear in no report at all.

**A number no script regenerates goes stale silently.** This test is the cheapest
possible check on that: each entry names a figure, the exact string as CLAUDE.md
writes it, and the report it must come from. When a report is regenerated and a
value moves, this fails and CLAUDE.md has to be corrected rather than drifting.

It is deliberately a CURATED list rather than a scanner. A scanner over every
number in the file would flag arithmetic, dates and prose, and a check that cries
wolf is one everybody learns to skip. These are the figures a reader is most
likely to quote at somebody.
"""

from __future__ import annotations

import pytest

from football_betting_lab.config import OUTPUTS_DIR, PROJECT_ROOT


CLAUDE_MD = PROJECT_ROOT / "CLAUDE.md"

#: (what it is, the literal as CLAUDE.md writes it, the report it comes from).
#: CLAUDE.md uses a unicode minus; the reports use ASCII. Both spellings are
#: accepted on each side so the test checks the VALUE, not the typography.
CLAIMS = [
    ("forecast skill, model Brier", "0.26106", "nfl_forecast_skill.md"),
    ("forecast skill, market Brier", "0.22782", "nfl_forecast_skill.md"),
    ("forecast skill, bets scored", "78,253", "nfl_forecast_skill.md"),
    ("forecast skill, 2024 calibrated", "0.23178", "nfl_forecast_skill.md"),
    ("forecast skill, 2025 calibrated", "0.22573", "nfl_forecast_skill.md"),
    ("encompassing, c", "+0.0695", "nfl_encompassing.md"),
    ("encompassing, placebo c", "+0.0081", "nfl_encompassing.md"),
    ("team ladder, pooled ROI", "-9.8%", "nfl_team_ladder_backtest.md"),
    ("team ladder, pooled bets", "54,641", "nfl_team_ladder_backtest.md"),
    ("team ladder, worst market", "-17.4%", "nfl_team_ladder_backtest.md"),
    ("null baseline, pooled ROI", "-9.29%", "nfl_null_baseline.md"),
    ("null baseline, bets", "366,725", "nfl_null_baseline.md"),
]


def _both_spellings(text: str) -> str:
    return text.replace("−", "-")


@pytest.mark.parametrize(
    "label,literal,report", CLAIMS, ids=[c[0] for c in CLAIMS]
)
def test_a_headline_figure_appears_in_the_report_that_produced_it(
    label: str, literal: str, report: str
) -> None:
    path = OUTPUTS_DIR / report
    assert path.is_file(), f"{report} is not committed, so {label} cannot be checked."
    assert _both_spellings(literal) in _both_spellings(
        path.read_text(encoding="utf-8")
    ), (
        f"CLAUDE.md quotes {label} as {literal}, and {report} does not contain "
        "that value. Regenerate the report, read what it now says, and correct "
        "CLAUDE.md — do not edit this test to match the prose."
    )


@pytest.mark.parametrize(
    "label,literal,report", CLAIMS, ids=[c[0] for c in CLAIMS]
)
def test_claude_md_still_quotes_the_figure_this_test_pins(
    label: str, literal: str, report: str
) -> None:
    """The other direction. If CLAUDE.md stops quoting a figure, the entry above
    is checking a report against nothing and quietly passes forever."""
    assert _both_spellings(literal) in _both_spellings(
        CLAUDE_MD.read_text(encoding="utf-8")
    ), (
        f"CLAUDE.md no longer quotes {label} ({literal}). Either it was removed "
        "on purpose — in which case drop the entry from CLAIMS — or a figure "
        "was silently reworded and this check had stopped checking anything."
    )
