#!/usr/bin/env python3
"""Assemble every measurement into one reviewable artifact, and stop.

    PYTHONPATH=src python scripts/run_allowlist_evidence.py

This allowlists nothing. It is step four of the six in
`docs/provider_allowlist_approval.md`; step six is Cooper's.
"""

from __future__ import annotations

import argparse
import math
import re
import sys
from statistics import NormalDist

import pandas as pd

from football_betting_lab.config import OUTPUTS_DIR, RAW_DIR
from football_betting_lab.leagues import DEFAULT_LEAGUE_KEY, league_for
from football_betting_lab.providers.historical import CACHE_DIRNAME
from football_betting_lab.reports import allowlist_evidence as bundle_module
from football_betting_lab.reports.allowlist_evidence import (
    Bar,
    EvidenceBundle,
    MarketEvidence,
)
from football_betting_lab.reports.price_sensitivity import (
    from_implied,
    measure as measure_prices,
    profit,
    to_implied,
)
from football_betting_lab.reports.props_backtest import (
    MINIMUM_BETS,
    coverage_line,
    label_snapshots,
    load_bought_prices,
    load_scored_bets,
)
from football_betting_lab.reports.settlement_agreement import (
    IMPLIED_GAP_TOLERANCE,
    suspects_and_screened,
)

#: Markets the compound simulation prices. The split between these and the
#: count-only markets is the strongest structure in the evidence.
COMPOUND = {
    "rush_yards", "rush_attempts", "rush_longest", "receptions",
    "reception_yards", "reception_longest", "pass_yards", "pass_completions",
    "pass_longest_completion",
}

#: Minimum share of quoting books at which a market must be positive.
MIN_BOOK_SHARE = 0.6

def read_null_baseline(path) -> float:
    """The harness figure, read from the null baseline's own report.

    It was a module constant, transcribed by hand. That is a copy of a number
    whose original is regenerated by a script, and the copy was stale within a
    day of the settlement fix — this bundle stated a harness figure from a run
    whose bets no longer existed. Reading it means the two cannot disagree,
    and a missing report is an error rather than a remembered value.
    """
    if not path.is_file():
        raise FileNotFoundError(
            f"No null baseline at {path}. Run scripts/run_null_baseline.py "
            "before assembling evidence: without it nothing here knows "
            "whether the harness returns the vig."
        )
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("| **all**"):
            match = re.search(r"(-?\d+\.\d+)%", line)
            if match:
                return float(match.group(1)) / 100.0
    raise ValueError(f"{path} has no pooled row, so the harness is unknown.")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--league", default=DEFAULT_LEAGUE_KEY)
    args = parser.parse_args(argv)
    league = league_for(args.league)

    null_roi = read_null_baseline(
        OUTPUTS_DIR / league.output_name("null_baseline", ".md")
    )
    bets_path = OUTPUTS_DIR / league.output_name("props_backtest_bets", ".csv")
    settle_path = OUTPUTS_DIR / league.output_name("settlement_agreement", ".md")
    if not bets_path.is_file():
        print(f"No backtest bets at {bets_path}.", file=sys.stderr)
        return 2

    bets = load_scored_bets(bets_path)
    staked = bets[bets["outcome"] != "void"].copy()
    staked["line"] = pd.to_numeric(staked["line"], errors="coerce")
    prices = label_snapshots(
        load_bought_prices(RAW_DIR / league.data_dir_segment / CACHE_DIRNAME, league)
    )
    prices = prices[prices["phase"] == "card"]
    sensitivity = {m.market: m for m in measure_prices(bets, prices)}

    # Read from the screen's own output so the two cannot drift apart, and
    # kept as two sets: what it flagged, and what it looked at.
    suspects, screened = (
        suspects_and_screened(settle_path.read_text(encoding="utf-8"))
        if settle_path.is_file()
        else (set(), set())
    )

    seasons = sorted(staked["season"].unique())
    families = staked["market"].nunique()
    factor = NormalDist().inv_cdf(1 - (0.05 / max(families, 1)) / 2) / 1.96

    evidence: list[MarketEvidence] = []
    for market in sorted(staked["market"].unique()):
        rows = staked[staked["market"] == market]
        entry = MarketEvidence(market=str(market), bets=len(rows))
        sens = sensitivity.get(str(market))

        entry.bars.append(
            Bar("harness", null_roi < 0,
                f"betting everything returns {null_roi:+.1%}")
        )
        if str(market) not in screened:
            entry.bars.append(
                Bar("settlement", False,
                    "never screened — the settlement report does not cover "
                    "this market, so nothing is known about whether it "
                    "settles on what it was priced on")
            )
        else:
            entry.bars.append(
                Bar("settlement", str(market) not in suspects,
                    "agrees with the devigged price"
                    if str(market) not in suspects
                    else f"realised rate sits more than {IMPLIED_GAP_TOLERANCE:.0%} from it")
            )
        if sens is None:
            entry.bars.append(Bar("consensus", False, "no consensus price computed"))
            entry.bars.append(Bar("books", False, "no book quoted enough"))
        else:
            entry.bars.append(
                Bar("consensus", sens.consensus_roi > 0,
                    f"{sens.consensus_roi:+.1%} at the median quote")
            )
            share = sens.books_positive / len(sens.books) if sens.books else 0.0
            entry.bars.append(
                Bar("books", share >= MIN_BOOK_SHARE,
                    f"positive at {sens.books_positive} of {len(sens.books)}")
            )
        # Replication: positive in every season with enough bets.
        per_season = rows.groupby("season")["profit"].agg(["size", "mean"])
        usable = per_season[per_season["size"] >= MINIMUM_BETS]
        replicated = len(usable) >= 2 and bool((usable["mean"] > 0).all())
        entry.bars.append(
            Bar("replication", replicated,
                ", ".join(
                    f"{int(s)} {row['mean']:+.1%} ({int(row['size'])})"
                    for s, row in per_season.iterrows()
                ) or "no season had enough bets")
        )
        entry.bars.append(
            Bar("sample", len(rows) >= MINIMUM_BETS,
                f"{len(rows):,} bets against a declared minimum of {MINIMUM_BETS}")
        )
        evidence.append(entry)

    result = EvidenceBundle(league=league.key, markets=evidence)
    result.inputs = {
        "Bought population": (
            f"816 games across {seasons[0]}-{seasons[-1]} — **every NFL game "
            "for which historical props exist.** The provider serves them "
            "only after 2023-05-03, so there is no more to buy."
        ),
        "Snapshots per game": "two priced (card time and the close), three bought",
        "Null baseline": f"{null_roi:+.1%} betting everything — harness sound",
        "Family correction": f"Bonferroni across {families} markets (x{factor:.2f})",
        "Settlement screen": f"{len(suspects)} suspect(s): {', '.join(sorted(suspects)) or 'none'}",
        "Selection gate": (
            "no player prop can produce a selection until the verdict "
            "`props_selectable_when_undesignated` is in force, which waits on "
            "one line in a book's did-not-play rules"
        ),
    }
    # Both of these used to be hand-written prose quoting numbers from a run
    # that had already been superseded. They are computed now, from the same
    # frame every other line in this bundle is computed from, because a
    # caveat that goes stale is worse than no caveat: it is a dead finding
    # stated with the authority of a freshly generated report.
    voided = bets[bets["outcome"] == "void"]
    if len(staked):
        as_void = float(staked["profit"].mean())
        graded = pd.concat(
            [staked["profit"], pd.Series([-1.0] * len(voided))], ignore_index=True
        )
        as_loss = float(graded.mean())
        dnp = (
            f"the whole record is {as_loss:+.1%} rather than {as_void:+.1%}, "
            f"across {len(voided):,} voided selections"
        )
    else:
        dnp = "nothing is staked, so there is nothing to grade"

    def _pooled_consensus(names: set[str]) -> str:
        """Bet-weighted mean of the per-market consensus returns."""
        entries = [
            sensitivity[m] for m in names
            if m in sensitivity
            and m not in suspects
            and sensitivity[m].consensus_bets
        ]
        if not entries:
            return "not measured"
        total = sum(e.consensus_bets for e in entries)
        roi = sum(e.consensus_roi * e.consensus_bets for e in entries) / total
        return f"{roi:+.1%} over {total:,} bets"

    priced = set(sensitivity)
    result.caveats = [
        "**The did-not-play rule.** Every return here assumes a book voids a "
        "prop for a player who takes no snap. If it grades them as losses, "
        f"{dnp}. One line in a book's rules, and no measurement can settle it.",
        "**There is no compound-versus-count split.** At the consensus price, "
        f"the compound-simulation markets pool to {_pooled_consensus(COMPOUND)} "
        f"and the count-only markets to {_pooled_consensus(priced - COMPOUND)}. "
        "An earlier version of this bundle reported that split as the "
        "strongest structure in the evidence. It was an artefact of two "
        "defects that touched only the compound markets — a walk-forward "
        "leak in the pooled per-play yardage file, and cross-season "
        "settlement — and it did not survive either fix.",
        "**The population cannot grow.** All 816 available games are bought. "
        "The only further evidence is forward, from 2026-09-09, at 272 games "
        "a season.",
        "**The NHL lab reached the same answer by a different route**: +1.4% "
        "over 4,830 bets became −1.6% over 73,918 once it bought its full "
        "population, and its approval was withdrawn. That is the direction "
        "of surprise to expect.",
    ]

    report = bundle_module.render(result)
    (OUTPUTS_DIR / league.output_name("allowlist_evidence", ".md")).write_text(
        report, encoding="utf-8"
    )
    print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
